services:

  server:
    build: server
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./server:/app

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/dist:/usr/share/nginx/html
      - ./layers:/usr/share/nginx/layers
    depends_on:
      - server

