services:

  server:
    build: server
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./server:/app
      - ./layers:/app/layers

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/data
