services:

  frontend:
    build: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_SERVER_URL=http://localhost:3000
      - VITE_TILES_URL=http://localhost:8080

  backend:
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - ./layers:/app/layers
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/data
