services:

  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    container_name: postgis
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGIS_GDAL_ENABLED_DRIVERS=ENABLE_ALL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/dist:/usr/share/nginx/html
    depends_on:
      - server

volumes:
  postgres_data:
