services:

  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./layers:/app/layers
    environment:
      - FASTAPI_ENV=${FASTAPI_ENV}

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8001:8080"
    volumes:
      - ./tileserver:/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    profiles:
      - dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./app/dist:/usr/share/nginx/html
      - ./layers:/usr/share/nginx/layers
    depends_on:
      - server
