export const layersConfig = {
    Temperature: 'tmp',
    'Apparent Temperature': 'aptmp',
    'Tropopause Temperature': 'trotmp',
    Precipitation: 'prate',
    'Low Cloud cover': 'lcdc',
    'Medium Cloud cover': 'mcdc',
    'High Cloud cover': 'hcdc',
    'Total Cloud cover': 'tcdc',
    Pressure: 'pres',
    Humidity: 'rh',
    Visibility: 'vis',
    'Wind speed (gust)': 'gust',
    'Sunshine duration': 'sunsd',
};
