services:

  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./tileserver:/data
      