"""add gfs schema

Revision ID: 37c350bd1ca5
Revises: 6b931e8d8cef
Create Date: 2024-05-26 13:30:39.043542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '37c350bd1ca5'
down_revision: Union[str, None] = '6b931e8d8cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create schema gfs')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime'),
    schema='gfs'
    )
    op.create_table('cycle_hours',
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['gfs.forecast_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key'),
    schema='gfs'
    )
    op.create_index(op.f('ix_gfs_cycle_hours_cycle_id'), 'cycle_hours', ['cycle_id'], unique=False, schema='gfs')
    op.create_table('rasters',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('rast', geoalchemy2.types.Raster(from_text='raster', name='raster'), nullable=True),
    sa.Column('cycle_hour_key', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_hour_key'], ['gfs.cycle_hours.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid'),
    schema='gfs'
    )
    op.create_index(op.f('ix_gfs_rasters_cycle_hour_key'), 'rasters', ['cycle_hour_key'], unique=False, schema='gfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gfs_rasters_cycle_hour_key'), table_name='rasters', schema='gfs')
    op.drop_table('rasters', schema='gfs')
    op.drop_index(op.f('ix_gfs_cycle_hours_cycle_id'), table_name='cycle_hours', schema='gfs')
    op.drop_table('cycle_hours', schema='gfs')
    op.drop_table('forecast_cycles', schema='gfs')
    # ### end Alembic commands ###
