"""init

Revision ID: 3a8da5f77bf4
Revises: 
Create Date: 2024-05-21 11:57:30.916796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3a8da5f77bf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create extension if not exists postgis_raster')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime')
    )
    op.create_table('cycle_hours',
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['forecast_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cycle_hours_cycle_id'), 'cycle_hours', ['cycle_id'], unique=False)
    op.create_table('rasters',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('rast', geoalchemy2.types.Raster(from_text='raster', name='raster'), nullable=True),
    sa.Column('cycle_hour_key', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_hour_key'], ['cycle_hours.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_rasters_cycle_hour_key'), 'rasters', ['cycle_hour_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rasters_cycle_hour_key'), table_name='rasters')
    op.drop_table('rasters')
    op.drop_index(op.f('ix_cycle_hours_cycle_id'), table_name='cycle_hours')
    op.drop_table('cycle_hours')
    op.drop_table('forecast_cycles')
    # ### end Alembic commands ###
