"""init

Revision ID: 614e0cd80a71
Revises: 
Create Date: 2024-05-19 17:50:08.362720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '614e0cd80a71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create extension postgis_raster')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raster_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_hour', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raster_metadata_forecast_hour'), 'raster_metadata', ['forecast_hour'], unique=True)
    op.create_table('rasters',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('rast', geoalchemy2.types.Raster(from_text='raster', name='raster'), nullable=True),
    sa.Column('forecast_hour', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_hour'], ['raster_metadata.forecast_hour'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_rasters_forecast_hour'), 'rasters', ['forecast_hour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rasters_forecast_hour'), table_name='rasters')
    op.drop_table('rasters')
    op.drop_index(op.f('ix_raster_metadata_forecast_hour'), table_name='raster_metadata')
    op.drop_table('raster_metadata')
    # ### end Alembic commands ###
