"""add is_complete

Revision ID: 6b931e8d8cef
Revises: 3a8da5f77bf4
Create Date: 2024-05-21 21:46:05.225087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b931e8d8cef'
down_revision: Union[str, None] = '3a8da5f77bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_cycles', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.execute("UPDATE forecast_cycles SET is_complete = false")
    op.alter_column('forecast_cycles', 'is_complete', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_cycles', 'is_complete')
    # ### end Alembic commands ###
